//
//  LogInInterfaces.swift
//  EvaluacionPokemon
//
//  Created by Sandra Sanchez on 07/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum LogInNavigationOption {
    case goToDashboard
}

protocol LogInWireframeInterface: WireframeInterface {
    func navigate(to option: LogInNavigationOption)
}

protocol LogInViewInterface: ViewInterface {
}

protocol LogInPresenterInterface: PresenterInterface {
    func goToDashboard()
}

protocol LogInInteractorInterface: InteractorInterface {
}
