//
//  LogInPresenter.swift
//  EvaluacionPokemon
//
//  Created by Sandra Sanchez on 07/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LogInPresenter {

    // MARK: - Private properties -

    private unowned let _view: LogInViewInterface
    private let _interactor: LogInInteractorInterface
    private let _wireframe: LogInWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: LogInWireframeInterface,
         view: LogInViewInterface,
         interactor: LogInInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension LogInPresenter: LogInPresenterInterface {
    func goToDashboard() {
        _wireframe.navigate(to: .goToDashboard)
    }
}
