//
//  LogInViewController.swift
//  EvaluacionPokemon
//
//  Created by Sandra Sanchez on 07/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LogInViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: LogInPresenterInterface!

    @IBOutlet weak var emailTextfield: UITextField!
    @IBOutlet weak var passwordTextfield: UITextField!
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    func validInputs(){
        if emailTextfield.text?.isEmpty ?? false || passwordTextfield.text?.isEmpty ?? false {
            print("Show alert textfield empty")
            presenter.goToDashboard()
        }else {
            presenter.goToDashboard()
        }
    }
    
    @IBAction func logInButton(_ sender: Any) {
        validInputs()
    }
}

// MARK: - Extensions -

extension LogInViewController: LogInViewInterface {
    
}
