//
//  LogInInteractor.swift
//  EvaluacionPokemon
//
//  Created by Sandra Sanchez on 07/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class LogInInteractor {
}

// MARK: - Extensions -

extension LogInInteractor: LogInInteractorInterface {
}
