//
//  LogInWireframe.swift
//  EvaluacionPokemon
//
//  Created by Sandra Sanchez on 07/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LogInWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: LogInViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = LogInInteractor()
        let presenter = LogInPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

    func openDashboard() {
        let nav = DashboardPokemonWireframe()
        navigationController?.pushWireframe(nav, animated: false)
    }
}

// MARK: - Extensions -

extension LogInWireframe: LogInWireframeInterface {

    func navigate(to option: LogInNavigationOption) {
        switch option {
        case .goToDashboard:
            openDashboard()
        }
    }
}
