//
//  DashboardPokemonInteractor.swift
//  EvaluacionPokemon
//
//  Created by Sandra Sanchez on 07/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import PokemonAPI

final class DashboardPokemonInteractor {
}

// MARK: - Extensions -

extension DashboardPokemonInteractor: DashboardPokemonInteractorInterface {
    func fetchPokemons(completion: @escaping (Result<[Pokemon], Error>) -> Void) {
        PokemonAPI().pokemonService.fetchPokemonList { result in
            switch result {
            case .success(let pokemon):
                print("list pokemon \(Pokemon)")
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
    }
    
}

struct Pokemon: Codable {
    let name: String
    let type: String
    let imageUrl: String
}
