//
//  DashboardPokemonInterfaces.swift
//  EvaluacionPokemon
//
//  Created by Sandra Sanchez on 07/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum DashboardPokemonNavigationOption {
}

protocol DashboardPokemonWireframeInterface: WireframeInterface {
    func navigate(to option: DashboardPokemonNavigationOption)
}

protocol DashboardPokemonViewInterface: ViewInterface {
    func failedFetchPkemons()
    func successFetchPokemons(pokemonList: [String])
}

protocol DashboardPokemonPresenterInterface: PresenterInterface {
    func fetchPokemons()
}

protocol DashboardPokemonInteractorInterface: InteractorInterface {
    func fetchPokemons(completion:  @escaping (_ result:Result<[Pokemon],Error>) -> Void)
}
