//
//  DashboardPokemonViewController.swift
//  EvaluacionPokemon
//
//  Created by Sandra Sanchez on 07/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//
import UIKit
import PokemonAPI

final class DashboardPokemonViewController: UIViewController {

    // MARK: - Public properties -
    var presenter: DashboardPokemonPresenterInterface!
    @IBOutlet weak var tableViewPokemons: UITableView!
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.fetchPokemons()
    }
}

// MARK: - Extensions -
extension DashboardPokemonViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        1
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        20
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "DetailPokemonCell") as! DetailPokemonCell
        return cell
    }
}

extension DashboardPokemonViewController: DashboardPokemonViewInterface {
    func successFetchPokemons(pokemonList: [String]) {
        
    }
    
    func failedFetchPkemons() {
        
    }
    
}
