//
//  DashboardPokemonPresenter.swift
//  EvaluacionPokemon
//
//  Created by Sandra Sanchez on 07/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DashboardPokemonPresenter {

    // MARK: - Private properties -

    private unowned let _view: DashboardPokemonViewInterface
    private let _interactor: DashboardPokemonInteractorInterface
    private let _wireframe: DashboardPokemonWireframeInterface

    // MARK: - Lifecycle -
    
    init(wireframe: DashboardPokemonWireframeInterface, view: DashboardPokemonViewInterface, interactor: DashboardPokemonInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension DashboardPokemonPresenter: DashboardPokemonPresenterInterface {
    func fetchPokemons() {
        _interactor.fetchPokemons { (result) in
            switch result {
            case .success(let favorites):
                self._view.successFetchPokemons(pokemonList: favorites)
            case .failure(let error):
                debugPrint(error.localizedDescription)
                self._view.failedFetchPkemons()
            break
            }
        }
    }
    
}
