//
//  DashboardPokemonWireframe.swift
//  EvaluacionPokemon
//
//  Created by Sandra Sanchez on 07/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DashboardPokemonWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -
    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: DashboardPokemonViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = DashboardPokemonInteractor()
        let presenter = DashboardPokemonPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DashboardPokemonWireframe: DashboardPokemonWireframeInterface {

    func navigate(to option: DashboardPokemonNavigationOption) {
    }
}
